apiVersion: v1
kind: Namespace
metadata:
  name: twistlock
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: twistlock-service-account
  namespace: twistlock
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: twistlock-clusterrole
rules:
- apiGroups: 
  - ""
  resources:
  - "namespaces"
  verbs: 
  - "create"
- apiGroups:
  - "apps"
  resources: 
  - "daemonsets"
  verbs: 
  - "list"
# Needed if Monitor Service Accounts, Collect Pod Labels or Monitor Istio is enabled
- apiGroups: 
  - "rbac.authorization.k8s.io"
  resources: 
  - "clusterroles"
  - "clusterrolebindings"
  verbs: 
  - "create"
- apiGroups: 
  - "rbac.authorization.k8s.io"
  resources: 
  - "clusterroles"
  resourceNames:
  - "twistlock-view"
  verbs:
  - "delete"
- apiGroups: 
  - "rbac.authorization.k8s.io"
  resources: 
  - "clusterrolebindings"
  resourceNames:
  - "twistlock-view-binding"
  verbs:
  - "delete"
# Needed for Monitoring Service Accounts
- apiGroups: 
  - "rbac.authorization.k8s.io"
  resources: 
  - "roles"
  - "rolebindings"
  - "clusterroles"
  - "clusterrolebindings"
  verbs: 
  - "list"
# Needed for Collecting Pod Labels
- apiGroups: 
  - "apps"
  resources: 
  - "deployments"
  - "replicasets"
  verbs: 
  - "get"
- apiGroups: 
  - ""
  resources: 
  - "namespaces"
  - "pods"
  verbs: 
  - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: twistlock-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: twistlock-service-account
  namespace: twistlock
roleRef:
  kind: ClusterRole
  name: twistlock-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
# Needed for deploying defender
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: twistlock-role
  namespace: twistlock
rules: 
- apiGroups: 
  - ""
  - "apps"
  resources: 
  - "secrets"
  - "services"
  - "serviceaccounts"
  - "daemonsets"
  verbs: 
  - "create"
- apiGroups: 
  - ""
  resources: 
  - "secrets"
  resourceNames:
  - "twistlock-secrets"
  verbs:
  - "delete"
- apiGroups: 
  - ""
  resources: 
  - "services"
  resourceNames:
  - "defender"
  verbs:
  - "delete"
- apiGroups: 
  - ""
  resources: 
  - "serviceaccounts"
  resourceNames:
  - "twistlock-service"
  verbs:
  - "delete"
- apiGroups: 
  - "apps"
  resources: 
  - "daemonsets"
  resourceNames:
  - "twistlock-defender-ds"
  verbs:
  - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: twistlock-rolebinding
  namespace: twistlock
subjects:
- kind: ServiceAccount
  name: twistlock-service-account
  namespace: twistlock
roleRef:
  kind: Role
  name: twistlock-role
  apiGroup: rbac.authorization.k8s.io