apiVersion: v1
kind: Namespace
metadata:
  name: twistlock-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: twistlock-service-account
  namespace: twistlock-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: twistlock-clusterrole-alt
rules:
- apiGroups: 
  - ""
  resources:
  - "namespaces"
  verbs: 
  - "create"
- apiGroups:
  - "apps"
  resources: 
  - "daemonsets"
  verbs: 
  - "list"
# Needed if Monitor Service Accounts, Collect Pod Labels or Monitor Istio is enabled
- apiGroups: 
  - "rbac.authorization.k8s.io"
  resources: 
  - "clusterroles"
  - "clusterrolebindings"
  verbs: 
  - "create"
# Needed for Monitoring Service Accounts
- apiGroups: 
  - "rbac.authorization.k8s.io"
  resources: 
  - "roles"
  - "rolebindings"
  - "clusterroles"
  - "clusterrolebindings"
  verbs: 
  - "list"
# Needed for Collecting Pod Labels
- apiGroups: 
  - "apps"
  resources: 
  - "deployments"
  - "replicasets"
  verbs: 
  - "get"
- apiGroups: 
  - ""
  resources: 
  - "namespaces"
  - "pods"
  verbs: 
  - "get"
# Needed for Istio Monitoring
- apiGroups: 
  - "security.istio.io"
  resources: 
  - "authorizationpolicies"
  - "peerauthentications"
  verbs: 
  - "list"
- apiGroups: 
  - "networking.istio.io"
  resources: 
  - "virtualservices"
  - "destinationrules"
  - "gateways"
  verbs: 
  - "list"
- apiGroups: 
  - ""
  resources: 
  - "pods"
  - "endpoints"
  - "services"
  verbs: 
  - "list"
- apiGroups: 
  - ""
  resources: 
  - "pods/proxy"
  verbs: 
  - "get"
# Needed for deploying defender
- apiGroups: 
  - ""
  - "apps"
  resources: 
  - "secrets"
  - "services"
  - "serviceaccounts"
  - "daemonsets"
  verbs: 
  - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: twistlock-clusterrolebinding-alt
subjects:
- kind: ServiceAccount
  name: twistlock-service-account
  namespace: twistlock-sa
roleRef:
  kind: ClusterRole
  name: twistlock-clusterrole-alt
  apiGroup: rbac.authorization.k8s.io